trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_ENV: 'production'
  NEXT_PUBLIC_BASE_URL: 'https://app.boomchainlab.com'
  NEXT_PUBLIC_CHAIN_ID: '8453'
  NEXT_PUBLIC_PROJECT_NAME: 'CHONK9K Earn'

stages:
  - stage: Build
    jobs:
      - job: BuildApp
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
          - script: |
              npm ci
              npm run build
            displayName: 'Build Next.js App'

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployFrontend
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureStaticWebApp@0
                  inputs:
                    app_location: '/'
                    output_location: '.next'
                    api_location: 'app/api'
                    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_TOKEN)